# Generated by Django 4.2 on 2024-01-14 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('coordinates', models.JSONField(default=list)),
                ('area', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('type', models.CharField(choices=[('INTRAVILAN', 'INTRAVILAN'), ('EXTRAVILAN', 'EXTRAVILAN')], default='INTRAVILAN', max_length=10)),
                ('destination', models.CharField(choices=[('CONSTRUCTII', 'CONSTRUCTII'), ('ARABIL', 'ARABIL'), ('FORESTIER', 'FORESTIER')], default='CONSTRUCTII', max_length=15)),
                ('open', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.region')),
                ('subregion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.subregion')),
            ],
        ),
    ]
