# Generated by Django 4.2 on 2024-01-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodel',
            name='coordinates',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
