# Generated by Django 4.2 on 2024-01-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_alter_locationmodel_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodel',
            name='area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
