# Generated by Django 4.2 on 2024-01-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationmodel',
            name='terms',
            field=models.BooleanField(default=False),
        ),
    ]
